//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Scripts/Player/Inputs/InputsControl.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputsControl : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputsControl()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputsControl"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""c8adf43d-5d7c-41d8-9519-37c787acaa71"",
            ""actions"": [
                {
                    ""name"": ""SpinWheel"",
                    ""type"": ""Button"",
                    ""id"": ""6ec361dc-83bb-4953-b8a6-0fd57521dc69"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StopWheel"",
                    ""type"": ""Button"",
                    ""id"": ""1fc64945-e709-454b-a4d9-f97c34730173"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6da64e16-edc7-49dd-9b44-0805c68f4cbf"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpinWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""622eab59-7312-4112-9008-8285dfc66d76"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StopWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_SpinWheel = m_Player.FindAction("SpinWheel", throwIfNotFound: true);
        m_Player_StopWheel = m_Player.FindAction("StopWheel", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_SpinWheel;
    private readonly InputAction m_Player_StopWheel;
    public struct PlayerActions
    {
        private @InputsControl m_Wrapper;
        public PlayerActions(@InputsControl wrapper) { m_Wrapper = wrapper; }
        public InputAction @SpinWheel => m_Wrapper.m_Player_SpinWheel;
        public InputAction @StopWheel => m_Wrapper.m_Player_StopWheel;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @SpinWheel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpinWheel;
                @SpinWheel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpinWheel;
                @SpinWheel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSpinWheel;
                @StopWheel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStopWheel;
                @StopWheel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStopWheel;
                @StopWheel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStopWheel;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @SpinWheel.started += instance.OnSpinWheel;
                @SpinWheel.performed += instance.OnSpinWheel;
                @SpinWheel.canceled += instance.OnSpinWheel;
                @StopWheel.started += instance.OnStopWheel;
                @StopWheel.performed += instance.OnStopWheel;
                @StopWheel.canceled += instance.OnStopWheel;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnSpinWheel(InputAction.CallbackContext context);
        void OnStopWheel(InputAction.CallbackContext context);
    }
}
